---
- name: Ensure fail2ban installed
  apt: 
    name: fail2ban
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Copy fail2ban configuration into place
  template:
    src:  ubuntu.etc_fail2ban_jail.local.j2
    dest: /etc/fail2ban/jail.local
  notify: restart fail2ban

- name: Ensure fail2ban is started
  service:
    name:  fail2ban
    state: started

- name: Update sshd config to disallow root logins
  lineinfile:
    dest:   /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line:   "PermitRootLogin no"
    state:  present
  notify: restart ssh
  when: ( disallow_root_login )
