---
- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted
  when: ( fail2ban_start is not changed )
  notify: Trigger check fail2ban status after start

- name: restart ssh
  service:
    name: ssh
    state: restarted

- name: Trigger check fail2ban status after start
  shell: |
    sleep 10
    systemctl status fail2ban
  changed_when: False
